[deploy]
bucket = 'cldfrmn-artifacts'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://gadgetoolslabs.com'
EnvBackendUrl = 'https://api.gadgetoolslabs.com'
DDBMessageTable = 'CrdDdb-DynamoDBTable-XSA06D6A86Z2'