[deploy]
bucket = 'cldfrmn-artifacts'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'Warner-Bell/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "cdpipeline-cruddur-artifacts"
BuildSpec = 'backend-flask/buildspec.yml'